version: '3.8'

igo_by:
  restart: "no"
  volumes:
    - './opt/igo_by:z'
  ports:
    - '${BY_API_PORT_EXTERNAL}:8080'
    
volumes:
  igo-by-db-data:
    name: igo_by_db_data_${DEPLOY_ENV}
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "./data/by-volume-${DEPLOY_ENV}"
