version: '3.8'

en_passant:
  restart: "no"
  volumes:
    - './opt/en_passant:z'
  ports:
    - '${PASSANT_API_PORT_EXTERNAL}:8080'
    
volumes:
  en-passant-db-data:
    name: en_passant_db_data_${DEPLOY_ENV}
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "./data/passant-volume-${DEPLOY_ENV}"
