version: '3.8'

services:
  en_passant:
    build:
      context: .
    image: 'en/passant:${I_GO_BY_LABEL}'
    container_name: 'en_passant_${DEPLOY_ENV}'
    restart: 'unless-stopped'
    environment:
      PASSANT_FLASK_DEBUG: "${PASSANT_FLASK_DEBUG}"
      OTHER_ENV_VARIABLES: "${ENV_GO_HERE}"
    expose:
      - 8080
    networks:
      - en-net
      
networks:
  en-net:
    name: en_net_${DEPLOY_ENV}
